In [34]:
import pandas as pd
import numpy as np

In [35]:
m = np.arange(1,10).reshape([3,3])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
pd.DataFrame(m,columns = ["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

## DataFrame İsimlendirme

In [37]:
df = pd.DataFrame(m,columns = ["var1", "var2", "var3"])

In [38]:
df.ndim

2

In [39]:
df.size

9

In [40]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
df.shape

(3, 3)

In [42]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [43]:
df.tail()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [44]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [45]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['var1', 'var2', 'var3'], dtype='object')]

In [46]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
pd.DataFrame(a, columns = ["degerler"])

degerler
0         1
1         2
2         3
3         4
4         5
5         6
6         7
7         8
8         9

## Eleman işlemleri

In [48]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [49]:
sozluk = {"Var1":s1, "Var2":s2, "Var3":s3}

In [50]:
df = pd.DataFrame(sozluk)
df

Var1  Var2  Var3
0     5     4     4
1     9     0     7
2     9     4     6
3     0     0     1
4     5     9     6

In [51]:
df[0:2]

Var1  Var2  Var3
0     5     4     4
1     9     0     7

In [52]:
df.index = ["a","b","c","d","e"]

In [53]:
df

Var1  Var2  Var3
a     5     4     4
b     9     0     7
c     9     4     6
d     0     0     1
e     5     9     6

In [54]:
df["a":"c"]

Var1  Var2  Var3
a     5     4     4
b     9     0     7
c     9     4     6

# Çalışma Sayfam

In [55]:
n = np.arange(1,10).reshape((3,3))
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
seri33 = pd.DataFrame(n)
seri33

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [57]:
seri33.columns = "var1", "var2", "var3" 

In [58]:
seri33

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [60]:
seri33["var4"] = [10,11,12]

In [61]:
seri33

var1  var2  var3  var4
0     1     2     3    10
1     4     5     6    11
2     7     8     9    12

In [88]:
seri33.iloc[:3,0:3]

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [89]:
seri33.loc[:3,"var2"]

0    2
1    5
2    8
Name: var2, dtype: int32