# Neden NumPy?

* Numpy Array içerisinde tek tip veri tutar.

In [1]:
a = [1,2,3,4,5]
b= [6,7,8,9,10]

In [2]:
ab=[]

for i in range (0, len(a)):
    ab.append(a[i]*b[i])

print(ab)

[6, 14, 24, 36, 50]


In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [5]:
a*b

array([ 6, 14, 24, 36, 50])

## Numpy array oluşturmak

In [6]:
a = np.array([1,2,3,4,5])

In [7]:
type(a)

numpy.ndarray

* Numpy Array içerisinde tek tip veri tutar. aşağıda olduğu gibi.

In [8]:
np.array([3.14,4,2.44,2,23.32], dtype="float32")

array([ 3.14,  4.  ,  2.44,  2.  , 23.32], dtype=float32)

* burada **dtype="float32"** yazarak kendimizde veri tipini belirleyebiliriz.

## NumPy da sıfırdan veri oluşturmak

In [9]:
np.zeros(10, dtype=int) # burada sıfırlardan bana 10 elemanı bir array ver dedik ve bu elemanların tipi int olsun 'varsayılan olarak float64 gelirler'

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full((3,5), 3, dtype = int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [12]:
np.arange(0,45,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44])

In [13]:
np.linspace(0,50,10, dtype=int)

array([ 0,  5, 11, 16, 22, 27, 33, 38, 44, 50])

In [14]:
np.random.normal(15,6,(4,4))

array([[ 9.42867697,  7.71940644, 14.93007548,  7.30639838],
       [23.75003986, 24.43476506, 18.37560067,  2.98714666],
       [ 7.89768242, 15.47962699, 21.86628485, 23.87622401],
       [15.12923545, 12.10698983, 12.43780821,  9.32021496]])

In [15]:
np.random.randint(0,15,(2,4))

array([[ 3, 11,  0,  0],
       [ 2,  1,  7,  7]])

## NumPy array özellikleri

* **ndim:** Boyut sayısı
* **shape:** Boyut bilgisi
* **size:** Toplam eleman sayısı
* **dtype:** Array veri tipi

In [16]:
a = np.random.randint(10, size=10)
a

array([4, 8, 1, 9, 4, 3, 6, 1, 7, 8])

In [17]:
a.size # Toplam eleman sayısı

10

In [18]:
a.shape #Boyut Bilgisi

(10,)

In [19]:
a.dtype #Veri tipi

dtype('int32')

In [20]:
a.ndim # Boyut sayısı

1

In [21]:
b = np.random.randint(10, size = (3,5))
b

array([[0, 5, 7, 4, 0],
       [1, 8, 3, 2, 0],
       [3, 4, 7, 1, 2]])

In [22]:
b.ndim

2

In [23]:
b.shape

(3, 5)

In [24]:
b.size

15

In [25]:
b.dtype

dtype('int32')

### Resahpeing (yeniden boyutlandırma işlemi)

In [26]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
b = a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a.ndim

1

In [29]:
b.ndim

2

* bazen tek boyutlu bir array i 2 boyutlu array yaparız ama tutulan veriler tek boyutlu bir array seviyesinde olsun isteriz.

In [30]:
c = np.arange(5,15)
c

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
d = c.reshape(1,10)
d

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [32]:
c.ndim

1

In [33]:
d.ndim

2

### Concatenation (Birleştirme işlemi)

In [34]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [35]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

##### İki boyutlu array birleştirme

In [36]:
c = np.array([[1,2,3],
             [4,5,6]])

In [37]:
np.concatenate([c,c])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate([c,c], axis = 1) # axis= 1 sütun bazılı birleştirme demek.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [39]:
x = np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

### Splitting (Ayırma ) işlemleri

In [40]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

* burada split metoduna ilk olarak array-i veriyoruz sonrada hangi index ler arasında bölüneceğini yazıyoruz.

*  istersek aşağıdaki gibi atama işlemleri de yaparak arrayi kullanabiliriz.

In [41]:
a,b,c = np.split(x,[3,5])
a

array([1, 2, 3])

In [42]:
b

array([99, 99])

In [43]:
c

array([3, 2, 1])

##### İki boyutlu array ayırma.

In [44]:
y = np.arange(20).reshape(4,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

* buarda iki tane fonk var 1) vsplit yatayda arrayi ayırmak için 2) hsplit buda dikeyde arrayi ayırmak iin kullanılır.

In [45]:
a,b=np.vsplit(y,[2])
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
c,d = np.hsplit(y,[2])
c

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16]])

In [48]:
d

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

### Sorting (Sıralama) İşlemi

In [49]:
z = np.random.normal(20,4,[4,4])
z

array([[20.98587444, 15.1997276 , 15.38649492, 20.70623178],
       [21.48865677, 22.1970762 , 15.31041918, 22.13175763],
       [24.35316367, 17.07931099, 15.20609798, 20.15096477],
       [20.70408694, 24.62756557, 24.26406344, 16.49946591]])

* buraada iki şekilde sorting işlemi yapılabiri. 1) her satır kendi arasında 2) her sütun kendi arasında.

* buarda axis=1 olunca row da sıralama yapıyor.

In [50]:
np.sort(z,axis=1)

array([[15.1997276 , 15.38649492, 20.70623178, 20.98587444],
       [15.31041918, 21.48865677, 22.13175763, 22.1970762 ],
       [15.20609798, 17.07931099, 20.15096477, 24.35316367],
       [16.49946591, 20.70408694, 24.26406344, 24.62756557]])

* buarda axis=0 olunca coulmn da sıralama yapıyor.

In [51]:
np.sort(z, axis=0)

array([[20.70408694, 15.1997276 , 15.20609798, 16.49946591],
       [20.98587444, 17.07931099, 15.31041918, 20.15096477],
       [21.48865677, 22.1970762 , 15.38649492, 20.70623178],
       [24.35316367, 24.62756557, 24.26406344, 22.13175763]])

### Array lerde index işlemleri

In [52]:
q = np.arange(10)
q

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
q[:5]

array([0, 1, 2, 3, 4])

In [54]:
qw = np.random.randint(10, size=[3,5])
qw

array([[5, 0, 5, 9, 7],
       [1, 2, 5, 1, 7],
       [1, 8, 8, 4, 5]])

In [55]:
qw[1,4]

7

In [56]:
qw[0,2] = 99999

In [57]:
qw

array([[    5,     0, 99999,     9,     7],
       [    1,     2,     5,     1,     7],
       [    1,     8,     8,     4,     5]])

#### İki boyutlu array lerde slicing işlemleri 

In [58]:
dizi = np.random.randint(15, size = [5,5])
dizi

array([[ 9, 13,  6, 12, 13],
       [ 4,  9,  3,  2,  2],
       [10, 10,  4,  4,  5],
       [ 5,  2,  3,  4,  1],
       [ 6,  3,  7,  8,  9]])

In [59]:
dizi[:,0] # bütün satırlar ve ilk sütunu getir.

array([ 9,  4, 10,  5,  6])

In [60]:
dizi[2:4,1:4]

array([[10,  4,  4],
       [ 2,  3,  4]])

In [61]:
dizi [2:4,0:2]

array([[10, 10],
       [ 5,  2]])

#### Alt küme üzerinde işlem yapmak 

In [62]:
a = np.random.randint(16, size=[5,5])
a

array([[ 9, 11, 13,  4,  8],
       [12, 13, 12,  1, 12],
       [11,  8, 10, 13, 11],
       [14,  2,  7, 15,  4],
       [11, 13, 10,  5, 12]])

In [63]:
alt_a=a[1:4,1:4]
alt_a

array([[13, 12,  1],
       [ 8, 10, 13],
       [ 2,  7, 15]])

In [64]:
alt_a[0,0]=99999

In [65]:
alt_a

array([[99999,    12,     1],
       [    8,    10,    13],
       [    2,     7,    15]])

In [66]:
a

array([[    9,    11,    13,     4,     8],
       [   12, 99999,    12,     1,    12],
       [   11,     8,    10,    13,    11],
       [   14,     2,     7,    15,     4],
       [   11,    13,    10,     5,    12]])

In [67]:
b = np.random.randint(16, size=[5,5])
b

array([[ 7, 13, 14, 12,  6],
       [10, 13,  1, 11,  6],
       [ 8,  4,  8, 10, 11],
       [ 2, 10, 14,  7,  3],
       [10,  2,  5,  1, 11]])

* burada copy() metodu kullanılarak ana veri kümesine etki edilmeden alt kme üzerinde işlem yapılabilinir.

In [68]:
alt_b =b[1:4,1:4].copy()
alt_b

array([[13,  1, 11],
       [ 4,  8, 10],
       [10, 14,  7]])

In [69]:
alt_b[0,0]=99999

In [70]:
alt_b

array([[99999,     1,    11],
       [    4,     8,    10],
       [   10,    14,     7]])

In [71]:
b

array([[ 7, 13, 14, 12,  6],
       [10, 13,  1, 11,  6],
       [ 8,  4,  8, 10, 11],
       [ 2, 10, 14,  7,  3],
       [10,  2,  5,  1, 11]])

#### Fancy index ile eelemanlara erişmek

In [72]:
v  = np.arange(10)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
v[1]

1

In [74]:
v[4]

4

In [75]:
v[7]

7

In [76]:
[v[3], v[2], v[7]]

[3, 2, 7]

* **İşte buradaki işleme fancy işlemi denir.**

In [77]:
al_getir=[1,3,5]

In [78]:
v[al_getir]

array([1, 3, 5])

* İki boyutlu array lerde fancy işlemleri

In [79]:
m = np.arange(9).reshape([3,3])
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [81]:
m[satir,sutun]

array([1, 5])

In [82]:
import numpy as np
m = np.array([[1, 2], [3, 4], [5, 6]])
condition = m > 3
selected_elements = m[condition]
# Sonuç nedir?


print(selected_elements)

[4 5 6]


In [83]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
result

array([[19, 22],
       [43, 50]])

In [84]:
import numpy as np

A = np.array([[1, 2], [3, 4], [5, 6]])
transposed_A = np.transpose(A)
transposed_A

array([[1, 3, 5],
       [2, 4, 6]])

In [85]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = A + B
result

array([[ 6,  8],
       [10, 12]])

In [86]:
import numpy as np

arr = np.arange(10, 20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [87]:
import numpy as np

I = np.eye(3) # 3x3 boyutunda birim matris
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
selected_row = A[1, :]
selected_column = A[:, 2]
selected_column

array([3, 6, 9])

In [89]:
import numpy as np

arr = np.full((2, 3), 7) # 2x3 boyutunda değeri 7 olan dizi
arr

array([[7, 7, 7],
       [7, 7, 7]])