# Pandas Series Oluşturmak

## Temel Pandas İşlemleri

In [1]:
import pandas as pd

In [2]:
seri = pd.Series([11,22,33,44,55,66,77,88,99])
seri

0    11
1    22
2    33
3    44
4    55
5    66
6    77
7    88
8    99
dtype: int64

In [3]:
type(seri) # veri tipi

pandas.core.series.Series

In [4]:
seri.axes

[RangeIndex(start=0, stop=9, step=1)]

In [5]:
seri.dtype

dtype('int64')

In [6]:
seri.values

array([11, 22, 33, 44, 55, 66, 77, 88, 99], dtype=int64)

In [7]:
seri.ndim

1

In [8]:
seri.size

9

In [9]:
seri.head() # seri dizisindeki ilk 5 elemanı bize gösterir.

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [10]:
seri.tail() # seri dizisindeki son 5 elemanı bize gösterir.

4    55
5    66
6    77
7    88
8    99
dtype: int64

## İndex isimlendirme

In [11]:
pd.Series([12,13,453,563,65,55], index = [1,3,5,7,9,11])

1      12
3      13
5     453
7     563
9      65
11     55
dtype: int64

In [12]:
seri2= pd.Series([12,13,453,563,65,55], index = ["a","b","c","d","e","f"])

In [13]:
seri2["a"]

12

In [14]:
seri2["a":"e"]

a     12
b     13
c    453
d    563
e     65
dtype: int64

* Sözlük üzerinden liste(series) oluşturmak

In [15]:
sozluk = pd.Series({"gun":10, "ay":8, "yıl":2012})
sozluk

gun      10
ay        8
yıl    2012
dtype: int64

In [16]:
sozluk2 = {"gun":10, "ay":8, "yıl":2012}

In [17]:
seri3 = pd.Series(sozluk)
seri3

gun      10
ay        8
yıl    2012
dtype: int64

## İki seriyi birleştirerek seri oluşturma

In [18]:
pd.concat([seri3,seri3])

gun      10
ay        8
yıl    2012
gun      10
ay        8
yıl    2012
dtype: int64

* bunları yan ya birleştirilemezler çğnk serier genlede bir boyutludur.

In [19]:
import pandas as pd
import numpy as np

In [20]:
m = np.arange(1,10).reshape([3,3])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
pd.DataFrame(m,columns = ["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

## DataFrame İsimlendirme

In [22]:
df = pd.DataFrame(m,columns = ["var1", "var2", "var3"])

In [23]:
df.ndim

2

In [24]:
df.size

9

In [25]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
df.shape

(3, 3)

In [27]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [28]:
df.tail()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [29]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [30]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['var1', 'var2', 'var3'], dtype='object')]

In [31]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
pd.DataFrame(a, columns = ["degerler"])

degerler
0         1
1         2
2         3
3         4
4         5
5         6
6         7
7         8
8         9

## DataFrame Eleman işlemleri

In [33]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [34]:
sozluk = {"Var1":s1, "Var2":s2, "Var3":s3}

In [35]:
df = pd.DataFrame(sozluk)
df

Var1  Var2  Var3
0     1     1     5
1     5     3     1
2     8     2     4
3     9     8     8
4     7     2     1

In [36]:
df[0:2]

Var1  Var2  Var3
0     1     1     5
1     5     3     1

In [37]:
df.index = ["a","b","c","d","e"]

In [38]:
df

Var1  Var2  Var3
a     1     1     5
b     5     3     1
c     8     2     4
d     9     8     8
e     7     2     1

In [39]:
df["a":"c"]

Var1  Var2  Var3
a     1     1     5
b     5     3     1
c     8     2     4

### Silme işlemi

In [40]:
s1 = np.random.randint(0,16,(5,3))
s1

array([[10, 12,  5],
       [ 3,  7,  6],
       [ 9, 15,  0],
       [11, 13,  1],
       [14,  3, 12]])

In [41]:
df = pd.DataFrame(s1, index = ["a","b","c","d","e"], columns=["Var1","Var2","Var3"])
df

Var1  Var2  Var3
a    10    12     5
b     3     7     6
c     9    15     0
d    11    13     1
e    14     3    12

In [42]:
df.drop("a",axis=0) # burada ilk argüman silinecek olan satır yada satırlardır. ikinci arguman axis ise satırlarda mı yoksa sütünlarda mı olduğu anlamına geliyor.

Var1  Var2  Var3
b     3     7     6
c     9    15     0
d    11    13     1
e    14     3    12

* burada dikkat edilmesi gereken asıl kısım şudur. bu işlem ana veri seti üzerinde kalıcı işlem yapmaz kalıcı işlem için 'inplace = True ' komutunu kullanmalaıyız.

* Funcy ile çoklu satır silme

In [43]:
k = ["c", "d"]

In [44]:
df.drop(k, axis=0)

Var1  Var2  Var3
a    10    12     5
b     3     7     6
e    14     3    12

* Değişkenlerde (Columns) Da sorgulama

In [45]:
"Var1" in df

True

In [46]:
l = ["Var1","Var3","Var4"] 

In [47]:
for i in l:
    print(i in df)

True
True
False


### Yeni Değişken (Column oluşturma)

In [48]:
df["Var4"]  = df["Var1"]*df["Var2"]

In [49]:
df

Var1  Var2  Var3  Var4
a    10    12     5   120
b     3     7     6    21
c     9    15     0   135
d    11    13     1   143
e    14     3    12    42

In [50]:
df["Var5"] = np.arange(0,5)
df

Var1  Var2  Var3  Var4  Var5
a    10    12     5   120     0
b     3     7     6    21     1
c     9    15     0   135     2
d    11    13     1   143     3
e    14     3    12    42     4

### Değişken (Column) Silmek

In [51]:
df.drop("Var5", axis=1, inplace=True) # Kalıcı silmek için inplace komutu kullanılabilinir. ve sütün dan silme işlemi yapmak için axis=1 olamlıdır.

In [52]:
df

Var1  Var2  Var3  Var4
a    10    12     5   120
b     3     7     6    21
c     9    15     0   135
d    11    13     1   143
e    14     3    12    42

## Gözlem (İndex) ve Değişken(Column) Seçimi (Loc & İloc)

In [53]:
m = np.random.randint(1, 30, size =(10,3))
m

array([[10, 13,  9],
       [21, 25, 21],
       [ 4,  7, 20],
       [15, 14,  1],
       [26, 13, 20],
       [20, 12,  8],
       [13, 20, 11],
       [ 1, 28, 11],
       [23,  3, 26],
       [26, 17, 22]])

In [54]:
df = pd.DataFrame(m, columns=["var1", "var2", "var3"])
df

var1  var2  var3
0    10    13     9
1    21    25    21
2     4     7    20
3    15    14     1
4    26    13    20
5    20    12     8
6    13    20    11
7     1    28    11
8    23     3    26
9    26    17    22

* Loc = Tanımlandığı şekli ile seçim yapmak için kullanılır.

In [55]:
df.iloc[0:3] # başlangıç değeri dahil son değer dahil değil.

var1  var2  var3
0    10    13     9
1    21    25    21
2     4     7    20

In [56]:
df.loc[0:3] # hem başlangıç hem de son değerler dahil.

var1  var2  var3
0    10    13     9
1    21    25    21
2     4     7    20
3    15    14     1

In [57]:
df.loc[0:2,"var3"]

0     9
1    21
2    20
Name: var3, dtype: int32

In [58]:
df.iloc[0:2]["var3"]

0     9
1    21
Name: var3, dtype: int32

* Koşullu eleman işlemleri 

In [59]:
df

var1  var2  var3
0    10    13     9
1    21    25    21
2     4     7    20
3    15    14     1
4    26    13    20
5    20    12     8
6    13    20    11
7     1    28    11
8    23     3    26
9    26    17    22

In [60]:
df["var2"]

0    13
1    25
2     7
3    14
4    13
5    12
6    20
7    28
8     3
9    17
Name: var2, dtype: int32

In [61]:
df["var1"][0:4]

0    10
1    21
2     4
3    15
Name: var1, dtype: int32

In [62]:
df[0:4]["var1"]

0    10
1    21
2     4
3    15
Name: var1, dtype: int32

In [63]:
df[0:5][["var2","var3"]]

var2  var3
0    13     9
1    25    21
2     7    20
3    14     1
4    13    20

In [64]:
df[df.var1 > 15]["var1"]

1    21
4    26
5    20
8    23
9    26
Name: var1, dtype: int32

In [65]:
df[(df.var1 >15) & (df.var2<15)][["var1","var2"]]

var1  var2
4    26    13
5    20    12
8    23     3

## DataFrame Birleştirme

In [66]:
df

var1  var2  var3
0    10    13     9
1    21    25    21
2     4     7    20
3    15    14     1
4    26    13    20
5    20    12     8
6    13    20    11
7     1    28    11
8    23     3    26
9    26    17    22

In [67]:
df2 = df+99

In [68]:
df2

var1  var2  var3
0   109   112   108
1   120   124   120
2   103   106   119
3   114   113   100
4   125   112   119
5   119   111   107
6   112   119   110
7   100   127   110
8   122   102   125
9   125   116   121

In [69]:
pd.concat([df , df2], ignore_index=True) # Burada birleştirme işleminde iki dataframe üst üste eklenir indexler birşeltirilmez 
#indexleri birleştirmek için ise 'ignore_index=True' argümanı kullanılır.

var1  var2  var3
0     10    13     9
1     21    25    21
2      4     7    20
3     15    14     1
4     26    13    20
5     20    12     8
6     13    20    11
7      1    28    11
8     23     3    26
9     26    17    22
10   109   112   108
11   120   124   120
12   103   106   119
13   114   113   100
14   125   112   119
15   119   111   107
16   112   119   110
17   100   127   110
18   122   102   125
19   125   116   121

* yukardaki gibi farklı komutları bulmak için ?komutİfadesi yazılırsa o komutlarla ilgili info gelicektir.

In [70]:
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[NDFrame] | Mapping[HashableT, NDFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index',